### ISSUE TITLE
data

### ISSUE THREAD

**Issue by bule-1** [sashford/Honors-Thesis-Spencer-Ashford#1]
How do I convert files into pictures, and the images I convert are the same for each one

**Comment by sashford** [comment]
Sorry, I had meant to upload my code after I had cleaned it up a bit but then got busy and forgot.  I'll upload some of my python notebooks and there will be a section devoted to plotting.  It uses matplotlib to make a polar image using the numpy files.

**Comment by sashford** [comment]
@bule-1 See the plotting section towards the bottom of HonorsThesis.ipynb.

**Comment by bule-1** [comment]
thanks!
